
run1:
	pandoc -s --mathml -i -t dzslides README.md -o README.html

run2:
	pandoc -s --webtex -i -t slidy READMD.md -o README.html

run3:
	pandoc -s --mathjax -i -t revealjs README.md -o README.html
	