# 
# junit sort by name
# junit parameter test
# log4j
# property
#
# mvn run  : execute hello world
# mvn comp : compile the package
#

all: help

help:
	@echo "help"

cln:
	find ./ -name "*~" -delete

run:
	mvn exec:java

comp:
	mvn package
